export default {
  index: {
    title: 'Getting Started',
    type: 'page',
    theme: {
      layout: 'full',
      breadcrumb: false,
      sidebar: false,
      toc: false,
    },
  },
  '-- Umami --': { type: 'separator', title: 'Umami' },
  about: 'About',
  install: 'Install',
  updates: 'Updates',
  quickstart: 'Quickstart',
  configuration: 'Configuration',
  teams: 'Teams',
  'add-a-user': 'Add a User',
  'how-to': 'How To',
  '-- Tracking --': { type: 'separator', title: 'Tracking' },
  'tracker-functions': 'Tracker Functions',
  'tracker-configuration': 'Tracker Configuration',
  'track-events': 'Track Events',
  'event-data': 'Event Data',
  'distinct-ids': 'Distinct IDs',
  tags: 'Tags',
  links: 'Links',
  pixels: 'Pixels',
  '-- Analysis --': { type: 'separator', title: 'Analysis' },
  filtering: 'Filtering',
  sessions: 'Sessions',
  compare: 'Compare',
  breakdown: 'Breakdown',
  insights: 'Insights',
  goals: 'Goals',
  funnel: 'Funnel',
  journey: 'Journey',
  retention: 'Retention',
  utm: 'UTM',
  revenue: 'Revenue',
  attribution: 'Attribution',
  '-- Reference --': { type: 'separator', title: 'Reference' },
  'metric-definitions': 'Metric Definitions',
  integrations: 'Integrations',
  faq: 'FAQ',
  '-- Contributing --': { type: 'separator', title: 'Contributing' },
  'code-of-conduct': 'Code of Conduct',
  '---': { type: 'separator' },
  api: {
    title: 'API Reference',
    type: 'page',
  },
  guides: {
    title: 'Guides',
    type: 'page',
  },
  cloud: {
    title: 'Cloud',
    type: 'page',
  },
};
