export default {
  '-- API --': { type: 'separator', title: 'API' },
  index: 'Overview',
  authentication: 'Authentication',
  'sending-stats': 'Sending Stats',
  '-- Endpoints --': { type: 'separator', title: 'Endpoints' },
  admin: 'Admin',
  events: 'Events',
  links: 'Links',
  me: 'Me',
  pixels: 'Pixels',
  websites: 'Websites',
  'website-stats': 'Website Stats',
  realtime: 'Realtime',
  reports: 'Reports',
  sessions: 'Sessions',
  teams: 'Teams',
  users: 'Users',
  '-- Clients --': { type: 'separator', title: 'Clients' },
  'api-client': 'API Client',
  'node-client': 'Node Client',
};
