export default {
  '-- Cloud --': { type: 'separator', title: 'Cloud' },
  index: 'Overview',
  'sign-up': 'Sign Up',
  login: 'Login',
  teams: 'Teams',
  'email-reports': 'Email Reports',
  'ip-filters': 'IP Filters',
  notifications: 'Notifications',
  'delete-account': 'Delete Account',
  '-- Billing --': { type: 'separator', title: 'Billing' },
  subscription: 'Subscription',
  usage: 'Usage',
  '-- API --': { type: 'separator', title: 'API' },
  'api-key': 'API Key',
  '-- Data --': { type: 'separator', title: 'Data' },
  'export-data': 'Export Data',
  'import-data': 'Import Data',
  '-- Changelog --': { type: 'separator', title: 'Changelog' },
  'cloud-changelog': 'Cloud Changelog',
  'api-changelog': 'API Changelog',
  '-- Help --': { type: 'separator', title: 'Help' },
  faq: 'FAQ',
};
