export default {
  '-- Guides --': { type: 'separator', title: 'Guides' },
  index: 'Overview',
  'migrate-v1-v2': 'Migrate v1 to v2',
  'migrate-mysql-postgresql': 'Migrate MySQL to PostgreSQL',
  '-- Marketing --': { type: 'separator', title: 'Marketing' },
  'measure-campaigns': 'Measure Campaigns',
  '-- Hosting --': { type: 'separator', title: 'Hosting' },
  hosting: 'Hosting',
  'running-on-caprover': 'Running on CapRover',
  'running-on-digitalocean': 'Running on DigitalOcean',
  'running-on-northflank': 'Running on Northflank',
  'running-on-fly-io': 'Running on Fly.io',
  'running-on-forge': 'Running on Forge',
  'running-on-heroku': 'Running on Heroku',
  'running-on-koyeb': 'Running on Koyeb',
  'running-on-neon': 'Running on Neon',
  'running-on-netlify': 'Running on Netlify',
  'running-on-nodion': 'Running on Nodion',
  'running-on-planetscale': 'Running on PlanetScale',
  'running-on-qovery': 'Running on Qovery',
  'running-on-railway': 'Running on Railway',
  'running-on-sevalla': 'Running on Sevalla',
  'running-on-supabase': 'Running on Supabase',
  'running-on-vercel': 'Running on Vercel',
};
